// Story: 
// "A man entered a room containing a table. He wore a black suite. Then the man left the room". 

// We have three situations: s1, s2, s3:
// s1: nothing initially known
// s2: man has entered the room
// s3: man has exited the room

// New situations are generated by events.

// We generate new unique identifiers room1, sit1, table1, man1, sit2, sit3 etc
// while encoding the story to logic.

// The encoder has to understand that the room and the man is the same in all
// situations and thus use the same identifiers man1 and room1 in all situations.

//  * Event 1: A man entered a room containing a table. 

[

// initial status generated by the first sentence  

{"@logic":["isa","room1","room"]},
{"@logic":["isa","table1","table"]},
{"@logic":["in","table1","room1","sit1"]},

{"@logic":["isa","event1","event"]},  
{"@logic":["event_type","event1","enter"]},
{"@logic":["event_actor","event1","man1"]},
{"@logic":["event_target","event1","room1"]},

{"@logic":["isa","man1","man"]},
{"@logic":["situationfrom","event1","sit1"]},

// a default "unlikely anything is inside" rule for the initial situation

{"@logic":[["-in","?:X","?:Y","sit1"], ["$block",["$","in"],["in","?:X","?:Y","sit1"]]],
 "@confidence": 90},

    
// * Situation 2: generated by the entering event.

{"@logic":["situationto","event1","sit2"]},
{"@logic":["nextsituation","sit1","sit2"]},

//{"@logic":["in","man1","room1","sit2"]}, // this is generated by the entering rule
{"@logic":["in",["clothes","man1","sit1"],"room1","sit2"]},
{"@logic":["in",["carriedstuff","man1","sit1"],"room1","sit2"]},

/* // we use a generic rule instead
{"@logic":[["in","?:X","?:Y","sit1"],
           "=>",
           [["in","?:X","?:Y","sit2"],"|",["$block",["$","in"],["$not",["in","?:X","?:Y","sit2"]]]]]},

{"@logic":[["-in","?:X","?:Y","sit1"],
           "=>",
           [["-in","?:X","?:Y","sit2"],"|",["$block",["$","in"],["in","?:X","?:Y","sit2"]]]]},
*/

// * Situation 2 statement: He wore a black suit.

{"@logic":["color",["clothes","man1","sit2"],"#:black","sit2"]}, 
   // #:black says that #:black is not equal to #:red, #:dog, #:man1 etc: anything different

{"@logic":["clothingtype",["clothes","man1","sit2"],"suite","sit2"]},
   // no question examples for clothingtype: making questions is an exercise :)


// * Event 2: Then the man left the room.

{"@logic":["isa","event2","event"]},  
{"@logic":["event_type","event2","leave"]},
{"@logic":["event_actor","event2","man1"]},
{"@logic":["event_target","event2","room1"]},

{"@logic":["situationfrom","event2","sit2"]},
{"@logic":["situationto","event2","sit3"]},
{"@logic":["nextsituation","sit2","sit3"]},

/* // we use a generic rule instead
{"@logic":[["in","?:X","?:Y","sit2"],
           "=>",
           [["in","?:X","?:Y","sit3"],"|",["$block",["$","in"],["$not",["in","?:X","?:Y","sit3"]]]]]},

{"@logic":[["-in","?:X","?:Y","sit2"],
           "=>",
           [["-in","?:X","?:Y","sit3"],"|",["$block",["$","in"],["in","?:X","?:Y","sit3"]]]]},
*/

// rules for entering and exiting


{"@logic":[["&",["isa","?:E","event"],["event_type","?:E","enter"],["event_actor","?:E","?:A"],["event_target","?:E","?:T"],
                ["situationto","?:E","?:S"]],
           "=>",
           ["in","?:A","?:T","?:S"]]},


{"@logic":[["&",["isa","?:E","event"],["event_type","?:E","leave"],["event_actor","?:E","?:A"],["event_target","?:E","?:T"],
            ["situationto","?:E","?:S"]],
       "=>",
       ["-in","?:A","?:T","?:S"]]},

// rule for default persistance of being inside something

{"@logic":[[["in","?:X","?:Y","?:S1"],"&",["nextsituation","?:S1","?:S2"]],
          "=>",
          [["in","?:X","?:Y","?:S2"],"|",["$block",["$","in"],["$not",["in","?:X","?:Y","?:S2"]]]]]},

// rules for default persistance of clothes


{"@logic":[["&",[["clothes","?:X","?:S1"],"=","?:C1"],["nextsituation","?:S1","?:S2"]],
            "=>",
           [["=",["clothes","?:X","?:S2"],"?:C1"],"|",["$block",["$","color"],["$not",["=",["clothes","?:X","?:S2"],"?:C1"]]]]] },

// rules for default persistance of color 

{"@logic":[["&",["color","?:X","?:C","?:S1"],["nextsituation","?:S1","?:S2"]],
           "=>",
           [["color","?:X","?:C","?:S2"],"|",["$block",["$","color"],["$not",["color","?:X","?:C","?:S2"]]]]] },

// rules for uniqueness of color

//{"@logic": ["-=","black","red"]}, // we do not need this if we use #:black and #:red

{"@logic": [[["color","?:X","?:C","?:S"],"&",["!=","?:C","?:C1"]],
             "=>",
            ["-color","?:X","?:C1","?:S"]]},

// useless rules generating infinite amounts of stuff to avoid simple termination
/*    
{"@logic":[["-isa","?:X","?:Y"],["isa",["foo","?:X"],"?Y"]]},
{"@logic":[["-isa",["foo","?:X"],"?:Y"],["isa","?:X","?Y"]]},
*/

// default rule for persistance of not being inside

{"@logic":[[["-in","?:X","?:Y","?:S1"],"&",["nextsituation","?:S1","?:S2"]],
   "=>",
   [["-in","?:X","?:Y","?:S2"],"|",["$block",["$","in"],["in","?:X","?:Y","?:S2"]]]]},

// some questions to try

//{"@question": ["isa","?:X","man"]}
//{"@question": ["in","table1","room1","sit3"]}
//{"@question": ["in","chair1","room1","sit3"]}
// {"@question": ["in","man1","room1","sit2"]}
//{"@question": ["-in","man1","room1","sit1"]}  
//{"@question": ["-in","man1","room1","sit2"]}
{"@question": ["in","man1","room1","?:S"]}  // in which situations is there a man in the room?
//{"@question": ["-in","man1","room1","?:S"]}
//{"@question": ["=",["clothes","man1","sit2"],["clothes","man1","sit3"]]}
//{"@question": ["color",["clothes","man1","sit3"],"#:red","sit3"]}

]
